INHERIT: ../../mkdocs-base.yml

site_dir: ../../site/4.0

theme:
  version: "4.0"

plugins:
  - search
  - minify:
      minify_html: true
  - meta-descriptions

nav:
  - Product guides:
    - Home: index.md
  - "Open source: API Firewall":
    - API Firewall overview: api-firewall/overview.md
    - Running API Firewall on Docker: api-firewall/installation-guides/docker-container.md
    - Demos:
      - Running the example application and API Firewall with Docker Compose: api-firewall/demos/docker-compose.md
      - Wallarm API Firewall demo with Kubernetes: api-firewall/demos/kubernetes-cluster.md
    - API Firewall changelog: api-firewall/release-notes.md
  - Security testing:
    - Wallarm FAST Overview: fast/README.md
    - FAST Onboarding: fast/onboarding/onboarding.md
    - Quick start guide:
      - Deployment options: fast/qsg/deployment-options.md
      - FAST node deployment: fast/qsg/deployment.md
      - Setting the environment for testing: fast/qsg/test-preparation.md
      - Running the test: fast/qsg/test-run.md
      - Interpreting the testing results: fast/qsg/test-interpretation.md
    - FAST basic operations:
      - "How FAST operates: overview": fast/operations/internals.md
      - Test Policies:
        - Overview: fast/operations/test-policy/overview.md
        - Basic Policy Configuration: fast/operations/test-policy/general.md
        - Configuration of Point Processing Rules: fast/operations/test-policy/insertion-points.md
        - Configuration of Vulnerability Detection Process: fast/operations/test-policy/attacks-to-test.md
        - Configuration of Anomaly Detection Process:
          - Overview: fast/operations/test-policy/fuzzer-intro.md
          - Principles of Fuzzer Operation: fast/operations/test-policy/fuzzer-internals.md
          - Fuzzer Configuration: fast/operations/test-policy/fuzzer-configuration.md
        - Using Test Policies: fast/operations/test-policy/using-policy.md
        - Test Policy Examples: fast/operations/test-policy/examples.md
      - Creating FAST Node And Getting A Token: fast/operations/create-node.md
      - List of Environment Variables Used by a FAST Node: fast/operations/env-variables.md
      - Configuring Authentication of Test Runs: fast/operations/test-authentication.md
      - Creating A Test Run: fast/operations/create-testrun.md
      - Copying A Test Run: fast/operations/copy-testrun.md
      - Stopping The Recording Process: fast/operations/stop-recording.md
      - Checking of Test Run State: fast/operations/check-testrun-status.md
      - Getting the Report with Test Results: fast/operations/ci-mode-report.md
    - Integration into CI/CD:
      - Introduction: fast/poc/integration-overview.md
      - Integration Prerequisites: fast/poc/prerequisites.md
      - Integration via Wallarm API:
        - Principles and Stages: fast/poc/integration-overview-api.md
        - Running FAST Node: fast/poc/node-deployment.md
        - Stopping The Recording Process: fast/poc/stopping-recording.md
        - Waiting For The Testing to Finish: fast/poc/waiting-for-tests.md
        - Integration Examples:
          - Integration of FAST with CircleCI: fast/poc/examples/circleci.md
      - Integration via FAST Node:
        - Principles and Stages: fast/poc/integration-overview-ci-mode.md
        - Running FAST Node in Recording Mode: fast/poc/ci-mode-recording.md
        - Running FAST Node in Testing Mode: fast/poc/ci-mode-testing.md
        - Using FAST in Concurrent CI/CD Workflows: fast/poc/ci-mode-concurrent-pipelines.md
        - Examples of Integration:
          - CircleCI: fast/poc/examples/circleci-cimode.md
          - GitLab CI/CD: fast/poc/examples/gitlabcicd-cimode.md
          - Jenkins: fast/poc/examples/jenkins-cimode.md
          - Bamboo: fast/poc/examples/bamboo-cimode.md
          - Azure DevOps: fast/poc/examples/azure-devops-cimode.md
      - Integration via Plugins:
        - Jenkins: fast/poc/jenkins-plugin.md
        - CircleCI: fast/poc/circleci-orbs.md
    - FAST DSL:
      - FAST DSL Overview: fast/dsl/intro.md
      - The Logic of Extensions: fast/dsl/logic.md
      - The Phases Description:
        - The Collect Phase: fast/dsl/phase-collect.md
        - The Match Phase: fast/dsl/phase-match.md
        - The Modify Phase: fast/dsl/phase-modify.md
        - The Generate Phase: fast/dsl/phase-generate.md
        - The Send Phase: fast/dsl/phase-send.md
        - The Detect Phase:
          - The Detect Phase Description: fast/dsl/detect/phase-detect.md
          - The Detect Phase Parameters Description: fast/dsl/detect/parameters.md
          - How the Detect Phase Operates with Markers: fast/dsl/detect/markers.md
      - The Creation of FAST Extensions: fast/dsl/create-extension.md
      - Examples of the FAST Extensions:
        - Overview: fast/dsl/extensions-examples/overview.md
        - Examination of the Sample Application: fast/dsl/extensions-examples/app-examination.md
        - Creation of Modifying Extension: fast/dsl/extensions-examples/mod-extension.md
        - Creation of Nonmodifying Extension: fast/dsl/extensions-examples/non-mod-extension.md
      - Using the FAST Extensions: fast/dsl/using-extension.md
      - Creating Points for FAST Extensions:
        - Introduction: fast/dsl/points/intro.md
        - Basic Concepts: fast/dsl/points/basics.md
        - Parsers and Filters:
          - Parsers and Filters: fast/dsl/points/parsers.md
          - HTTP Parser and Its Filters: fast/dsl/points/parsers/http.md
          - Form-urlencoded parser: fast/dsl/points/parsers/form-urlencoded.md
          - Multipart parser: fast/dsl/points/parsers/multipart.md
          - Cookie parser: fast/dsl/points/parsers/cookie.md
          - XML Parser and Its Filters: fast/dsl/points/parsers/xml.md
          - Json_doc Parser and Its Filters: fast/dsl/points/parsers/json.md
          - Base64 parser: fast/dsl/points/parsers/base64.md
          - GZIP parser: fast/dsl/points/parsers/gzip.md
          - Array filter: fast/dsl/points/parsers/array.md
          - Hash filter: fast/dsl/points/parsers/hash.md
        - Points Building Principles: fast/dsl/points/principles.md
        - How to Build a Point: fast/dsl/points/construction.md          
    - Text Formatting Conventions: fast/AGREEMENTS.md
    - Glossary: fast/TERMS-GLOSSARY.md
    - Wallarm Clouds List: fast/CLOUD-LIST.md
    - Vulnerabilities List: fast/VULN-LIST.md
    - Configuration of Proxying Rules: fast/poc/proxy-configuration.md
    - Installing SSL Certificates:
      - Introduction: fast/ssl/intro.md
      - Installing Own Certificate for FAST Node: fast/ssl/install-certificate-on-fast-node.md
      - Installing the FAST Node Certificate for a Browser:
        - Apple Safari: fast/ssl/browsers-ssl/safari-ssl.md
        - Google Chrome: fast/ssl/browsers-ssl/chrome-ssl.md
        - Microsoft Edge: fast/ssl/browsers-ssl/edge-ssl.md
        - Microsoft Internet Explorer 11: fast/ssl/browsers-ssl/ie11-ssl.md
        - Mozilla Firefox: fast/ssl/browsers-ssl/firefox-ssl.md
    - Troubleshooting: fast/TSHOOT.md
  - API docs:
    - Wallarm API overview: api/overview.md
    - Wallarm API request examples: api/request-examples.md 
  - FAQ:
    - Installing Wallarm Ingress controller: faq/ingress-installation.md
    - Errors after Wallarm node installation: faq/common-errors-after-installation.md
    - Wallarm platform and third-party services interaction: faq/wallarm-and-third-party-services.md
    - Wallarm service status page: faq/wallarm-status-page.md
    - Wallarm Cloud is down: faq/wallarm-cloud-down.md
    - Tarantool troubleshooting: faq/tarantool.md
    - Attacks are not uploaded to the Wallarm Cloud: faq/attacks-not-uploaded-to-cloud.md
    - Addressing Wallarm node issues alerted by OWASP dashboards: faq/node-issues-on-owasp-dashboards.md
  - Demo videos:
    - Wallarm platform settings: demo-videos/overview.md
    - Analyzing CVEs and related attacks: demo-videos/events-inspection.md
#   - Wallarm Scanner overview: demo-videos/scanner-overview.md
#   - Wallarm FAST overview and integration options: demo-videos/fast-overview.md
    - API Discovery overview: demo-videos/api-discovery.md
    - API Abuse Prevention overview: demo-videos/api-abuse-prevention.md
    - API Leaks overview: demo-videos/api-leaks.md
  - Changelog & news: news.md
