// Copy page markdown to clipboard
// Fetches the .md companion generated by scripts/generate_raw_markdown.py,
// which sits next to the rendered page (e.g. /foo/bar/ ↔ /foo/bar.md) and
// has all snippets resolved and links rewritten to absolute URLs.
document.addEventListener('click', function(e) {
  var btn = e.target.closest('.md-clipboard-page');
  if (!btn) return;

  e.preventDefault();
  var fetchUrl = btn.getAttribute('data-clipboard-src');
  if (!fetchUrl) return;

  btn.classList.add('md-clipboard-page--active');

  function showSnackbar(message) {
    var dialog = document.querySelector('[data-md-component="dialog"]');
    if (!dialog) return;
    var inner = dialog.querySelector('.md-typeset');
    if (inner) inner.textContent = message;
    dialog.classList.add('md-dialog--active');
    setTimeout(function() {
      dialog.classList.remove('md-dialog--active');
    }, 2000);
  }

  fetch(fetchUrl)
    .then(function(res) {
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return res.text();
    })
    .then(function(text) {
      return navigator.clipboard.writeText(text);
    })
    .then(function() {
      btn.classList.remove('md-clipboard-page--active');
      showSnackbar('Copied to clipboard');
    })
    .catch(function(err) {
      btn.classList.remove('md-clipboard-page--active');
      console.error('Failed to copy markdown:', err);
      showSnackbar('Failed to copy — raw markdown is generated only after production deployment');
    });
});

// Page-actions dropdown: "Copy page" menu + "Add Docs MCP" section.
// Handles the caret toggle, outside-click / Escape close, and the generic
// copy-to-clipboard items (MCP server URL, Claude / Codex install commands).
(function () {
  function showPopSnackbar(message) {
    var dialog = document.querySelector('[data-md-component="dialog"]');
    if (!dialog) return;
    var inner = dialog.querySelector('.md-typeset');
    if (inner) inner.textContent = message;
    dialog.classList.add('md-dialog--active');
    setTimeout(function () {
      dialog.classList.remove('md-dialog--active');
    }, 2000);
  }

  function closeAllPagePops() {
    document.querySelectorAll('.md-page-pop__menu.is-open').forEach(function (menu) {
      menu.classList.remove('is-open');
      var caret = menu.parentElement && menu.parentElement.querySelector('[data-page-pop-toggle]');
      if (caret) caret.setAttribute('aria-expanded', 'false');
    });
  }

  document.addEventListener('click', function (e) {
    // Toggle the dropdown via the caret
    var toggle = e.target.closest('[data-page-pop-toggle]');
    if (toggle) {
      e.preventDefault();
      e.stopPropagation();
      var pop = toggle.closest('.md-page-pop');
      var menu = pop && pop.querySelector('[data-page-pop-menu]');
      if (!menu) return;
      var wasOpen = menu.classList.contains('is-open');
      closeAllPagePops();
      if (!wasOpen) {
        menu.classList.add('is-open');
        toggle.setAttribute('aria-expanded', 'true');
      }
      return;
    }

    // Generic copy items (MCP URL, Claude / Codex commands) — keep the menu open
    // so the user sees the confirmation tick.
    var copyBtn = e.target.closest('[data-page-copy]');
    if (copyBtn) {
      e.preventDefault();
      var val = copyBtn.getAttribute('data-page-copy');
      navigator.clipboard.writeText(val).then(function () {
        showPopSnackbar('Copied to clipboard');
      }).catch(function (err) {
        console.error('Failed to copy:', err);
        showPopSnackbar('Failed to copy to clipboard');
      });
      return;
    }

    // Clicks inside the menu: close after activating a link or the Markdown copy
    // (the Markdown copy is handled by the .md-clipboard-page listener above).
    var openMenu = e.target.closest('.md-page-pop__menu');
    if (openMenu) {
      if (e.target.closest('a.md-page-pop__mi, button.md-clipboard-page, .md-page-pop__foot a')) {
        setTimeout(closeAllPagePops, 50);
      }
      return;
    }

    // Click outside any menu — close all
    closeAllPagePops();
  });

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') closeAllPagePops();
  });

  // Close the dropdown on scroll: it is anchored to a button that lives in the
  // scrolling content, so an open menu would otherwise drift over the sticky
  // header/tabs. Capture phase catches scrolls on any scrollable ancestor.
  document.addEventListener('scroll', function () {
    if (document.querySelector('.md-page-pop__menu.is-open')) closeAllPagePops();
  }, true);
})();

// Open external links in new tab
var links = document.links;

for(var i = 0; i < links.length; i++) {
  if (links[i].hostname != window.location.hostname) {
    links[i].target = '_blank';
    links[i].rel = 'noopener';
  }
}

window.addEventListener('DOMContentLoaded', function() {
  const container = document.querySelector('.md-container');
  container.style.visibility = 'visible';
});

document.addEventListener('DOMContentLoaded', function() {
  let main = document.querySelector(".md-main");
  let isHomepage = location.pathname === "/" || location.pathname === "/4.4/" || location.pathname === "/4.2/" || location.pathname === "/4.6/" || location.pathname === "/4.8/" || location.pathname === "/4.10/" || location.pathname === "/5.x/" || location.pathname === "/7.x/" || location.pathname === "/index.html";
  if (main) {
    if (isHomepage) {
      main.classList.add('homepage');
    } else {
      main.classList.remove('homepage');
    }
  }
});

// Detect platform for search hotkey indicator
(function() {
  var platform = navigator.platform.toLowerCase();
  if (platform.indexOf('win') !== -1) {
    document.documentElement.classList.add('platform-windows');
  } else if (platform.indexOf('linux') !== -1) {
    document.documentElement.classList.add('platform-linux');
  } else if (platform.indexOf('mac') !== -1) {
    document.documentElement.classList.add('platform-mac');
  }
})();

// Ctrl+K / Cmd+K keyboard shortcut for search (works across all keyboard layouts)
document.addEventListener('keydown', function(e) {
  // Check for Ctrl+K (Windows/Linux) or Cmd+K (Mac)
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault();
    var searchToggle = document.getElementById('__search');
    if (searchToggle) {
      searchToggle.checked = true;
      // Focus the search input
      setTimeout(function() {
        var searchInput = document.querySelector('.md-search__input');
        if (searchInput) {
          searchInput.focus();
          searchInput.select();
        }
      }, 100);
    }
  }
});

function injectScript(src, cb) {
  let script = document.createElement('script');

  script.src = src;
  cb && (script.onload = cb);
  document.body.append(script);
}

// Add LeadFeeder
window.ldfdr = window.ldfdr || {};
injectScript('https://lftracker.leadfeeder.com/lftracker_v1_kn9Eq4Rwz5KaRlvP.js');

// Version selection

var rootVersion = '6.x';

// Show the list of available Wallarm versions

var lastVersionToggleAt = 0;
function versionClicked (event) {
  if (event) {
    event.preventDefault();
    event.stopPropagation(); /* prevent drawer from closing on mobile */
  }
  var now = Date.now();
  if (now - lastVersionToggleAt < 400) return; /* avoid double toggle (touchend + click) */
  lastVersionToggleAt = now;
  var list = document.getElementById('versionsList');
  var main = document.getElementById('versionsMain');
  if (!list || !main) return;
  if (list.style.display === 'none' || !list.style.display) {
    list.style.display = 'block';
    main.classList.add('versions-main-active');
    main.setAttribute('aria-expanded', 'true');
  } else {
    list.style.display = 'none';
    main.classList.remove('versions-main-active');
    main.setAttribute('aria-expanded', 'false');
  }
}

// Open the docs for selected Wallarm version and change value in the selector
function goToVersion (event, currentVersion, version) {
  event.preventDefault()

  if (currentVersion === version) {
    window.location.reload(false);
  }
  else {
    let tmp = window.location.pathname.split('/');
    window.top.location.href = tmp.join('/');

    if (version === rootVersion) {
      window.top.location.href = window.location.pathname.replace('/'+currentVersion+'/','/');
    } else {
      if (currentVersion === rootVersion) {
          window.top.location.href = window.location.pathname.replace('/','/'+version+'/');
      }
      else {
          window.top.location.href = window.location.pathname.replace('/'+currentVersion+'/','/'+version+'/')
      }
    }
  }
}

document.addEventListener('DOMContentLoaded', (event) => {
  var versionsDiv = document.getElementById('versionsDiv');
  if (versionsDiv) {
    versionsDiv.style.display = 'inline-block';
  }

  /* Version selector: delegation + touch so it works on mobile; list opens upward on small screens */
  function onVersionButtonClick(e) {
    if (!e.target.closest || !e.target.closest('#versionsMain')) return;
    e.preventDefault();
    e.stopPropagation();
    versionClicked(e);
  }
  document.addEventListener('click', onVersionButtonClick, true);
  document.addEventListener('touchend', function(e) {
    if (!e.target.closest || !e.target.closest('#versionsMain')) return;
    e.preventDefault();
    e.stopPropagation();
    versionClicked(e);
  }, { passive: false, capture: true });

  /* Close version list when clicking outside */
  function closeVersionsIfOutside(e) {
    var list = document.getElementById('versionsList');
    var div = document.getElementById('versionsDiv');
    if (!list || !div || list.style.display !== 'block') return;
    if (e.target.closest && e.target.closest('#versionsDiv')) return;
    list.style.display = 'none';
    var main = document.getElementById('versionsMain');
    if (main) {
      main.classList.remove('versions-main-active');
      main.setAttribute('aria-expanded', 'false');
    }
  }
  document.addEventListener('click', closeVersionsIfOutside, true);
  document.addEventListener('touchend', closeVersionsIfOutside, true);

  const addButtons = document.querySelectorAll('.md-header__button[for="__search"]');

  addButtons.forEach(button => {
    button.addEventListener('click', () => {
      document.body.classList.toggle('scrolllock');
    });
  });

  const removeButton = document.querySelector('.md-search__icon[for="__search"]');
  if (removeButton) {
    removeButton.addEventListener('click', () => {
      document.body.classList.remove('scrolllock');
    });
  }
});

// Stop scrolling if sidebar is open
document.addEventListener('DOMContentLoaded', (event) => {
  const sidebarToggle = document.querySelector('.md-header__button[for="__drawer"]');
  const overlay = document.querySelector('.md-overlay');

  if (sidebarToggle) {
    sidebarToggle.addEventListener('click', () => {
      if (document.documentElement.style.overflow === 'hidden') {
        document.documentElement.style.overflow = 'visible';
      } else {
        document.documentElement.style.overflow = 'hidden';
      }
    });
  }

  if (overlay) {
    overlay.addEventListener('click', () => {
      document.documentElement.style.overflow = 'visible';
    });
  }
});

// Mobile nav fix:
// Our custom nav template expands L1/L2 by default (inputs are checked),
// which can leave the Material mobile drawer "drilled down" into a random subtree
// (often the last expanded one, e.g. "FAQ"). When opening the drawer on mobile,
// reset the nav toggles to the active page's path.
function resetMobileDrawerNavigationToActivePath() {
  // Match Material's breakpoint where the drawer is used
  if (!window.matchMedia || !window.matchMedia("(max-width: 76.1875em)").matches) return;

  const sidebar = document.querySelector('.md-sidebar--primary');
  if (!sidebar) return;

  const navRoot =
    sidebar.querySelector('[data-md-component="navigation"]') ||
    sidebar.querySelector('.md-nav--primary');
  if (!navRoot) return;

  const allToggles = Array.from(navRoot.querySelectorAll('input.md-nav__toggle[data-md-toggle^="nav-"]'));
  if (!allToggles.length) return;

  // Find the active page link in the nav
  const activeLink = navRoot.querySelector('a.md-nav__link--active');
  if (!activeLink) {
    // Home or edge case: show root level (no drill-down)
    allToggles.forEach(t => (t.checked = false));
    return;
  }

  // Collect toggles on the active path (ancestors of the active link)
  const keep = new Set();
  let node = activeLink;
  while (node) {
    const nested = node.closest && node.closest('.md-nav__item--nested');
    if (!nested) break;

    // The toggle is an immediate child of the nested <li> in our template
    const toggle = Array.from(nested.children).find(
      el => el && el.matches && el.matches('input.md-nav__toggle')
    );
    if (toggle) keep.add(toggle);

    node = nested.parentElement;
  }

  allToggles.forEach(t => (t.checked = keep.has(t)));
}

document.addEventListener('DOMContentLoaded', () => {
  const drawerToggle = document.getElementById('__drawer');
  if (!drawerToggle) return;

  drawerToggle.addEventListener('change', () => {
    if (drawerToggle.checked) resetMobileDrawerNavigationToActivePath();
  });
});

// Open the Help block

function helpClicked (event) {
  if (document.getElementById('helpList').style.display === 'none') {
    document.getElementById('helpList').style.display = 'block'
    document.getElementById('helpMain').classList.add("help-main-active")
  } else {
    document.getElementById('helpList').style.display = 'none'
    document.getElementById('helpMain').classList.remove("help-main-active")
  }
}

// Always stick left navigation to the bottom of the header
document.addEventListener('DOMContentLoaded', () => {
  const updateSidebarPosition = () => {
    const sidebar = document.querySelector('.md-sidebar--primary');
    const header = document.querySelector('.md-header');
    const headerRect = header.getBoundingClientRect();
    const headerBottom = headerRect.bottom;
    document.documentElement.style.setProperty('--header-bottom', `${headerBottom}px`);
  };

  // call on load
  updateSidebarPosition();

  const toggleButton = document.querySelector('.md-header__button[for="__drawer"]');
  toggleButton.addEventListener('click', updateSidebarPosition);

  // call on window resize
  window.addEventListener('resize', updateSidebarPosition);
});





// Custom accordion behavior disabled - using MkDocs Material's native behavior
// If you want to re-enable custom accordion (collapse siblings when expanding):
// Uncomment the code below

/*
function getAllNavigationElements(element, selector){
  if(element.parentElement && element.parentElement.parentElement && element.parentElement.parentElement.children){
    let allChildren = element.parentElement.parentElement.children;
    for (let index = 0; index < allChildren.length; index++) {
      let child = allChildren[index];
      let navigationInput = child.querySelector(selector);
      if (navigationInput && navigationInput !== element){
        navigationInput.checked = false;
        navigationInput.parentElement.classList.remove('md-nav__item--expanded');
      }
    }
  }
}

document.addEventListener('change', function(event) {
  if (event.target.matches('.md-nav__toggle')) {
    getAllNavigationElements(event.target, '.md-nav__toggle');
    if (event.target.checked) {
      event.target.parentElement.classList.add('md-nav__item--expanded');
    } else {
      event.target.parentElement.classList.remove('md-nav__item--expanded');
    }
  }
}, false);
*/


// Expand and collapse supported platform cards on click

function platformClicked (event, platformId) {
  event.preventDefault();
  optionsId = platformId + 'Id';
  var activeOptions=document.getElementsByClassName('option-active');
  // console.log(this);

  if (activeOptions.length != 0) {
    for (let index = 0; index < activeOptions.length; index++) {
      if (activeOptions[index].children[0].children[3].id != this.optionsId) {
      document.getElementById(activeOptions[index].children[0].children[3].id).style.display = 'none';
      activeOptions[index].classList.remove("option-active");
      }
      else { console.log(this.optionsId) }
    }
    if (document.getElementById(optionsId).style.display === 'none') {
      document.getElementById(optionsId).style.display = 'block';
      document.getElementById(platformId).parentNode.classList.add("option-active");
    }
    else {
      document.getElementById(optionsId).style.display = 'none';
      document.getElementById(platformId).parentNode.classList.remove("option-active");
    }
  }
  else {
    if (document.getElementById(optionsId).style.display === 'none') {
      document.getElementById(optionsId).style.display = 'block';
      document.getElementById(platformId).parentNode.classList.add("option-active");
    }
    else {
      document.getElementById(optionsId).style.display = 'none';
      document.getElementById(platformId).parentNode.classList.remove("option-active");
    }
  }
}

// Cancel collapsing and expanding spported platform cards when clicking the links inside these cards

function noAction(event) {
  event.stopImmediatePropagation();
  return false;
}

// Highlight the search string if URL contains ?search

const urlParams = new URLSearchParams(window.location.search);
const myParam = urlParams.get('search');
var searchBar = document.getElementsByClassName('md-search__input');

if(myParam !== null) {
  document.getElementById("__search").checked = true;
}

// Show warning about deprecated version if it is opened

let paths = window.location.pathname.split('/');
var announceBar = document.getElementsByClassName("md-banner");
var announceBarText = document.getElementsByClassName("md-banner__inner");
if (paths[1] == '2.18' || paths[1] == '3.6') {
  for (var i = 0; i < announceBar.length; i++) {
    announceBar[i].style.display="block";
    announceBarText[i].innerHTML = 'Wallarm node 3.6 and lower are not supported. Please <a href="/updating-migrating/older-versions/what-is-new/" style="color:white; font-weight: bold;">upgrade</a> Wallarm modules to the latest version.';
 }
}

// ZoomInfo script

(function() {
    var zi = document.createElement('script');
    zi.type = 'text/javascript';
    zi.async = true;
    zi.referrerPolicy = 'unsafe-url';
    zi.src = 'https://ws.zoominfo.com/pixel/612ca1c28ffa1e00155b2895';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(zi, s);
})();

// iframe for Partner Portal

if (window.location.href.indexOf("channeltivity-content") > -1) {
  toggleChannelTivityClass();
  resizeObserve();
}

function toggleChannelTivityClass() {
  document.body.classList.add("channeltivity");
}

function resizeObserve() {
  if (!inIframe()) {
    return;
  }

  const CONTAINER_CLASS_NAME = ".md-content";
  const containerNode = document.querySelector(CONTAINER_CLASS_NAME);
  let latestHeight;

  const resizeObserver = new ResizeObserver(entries => {
    for (let entry of entries) {
      const cr = entry.contentRect;

      if (latestHeight !== cr.height) {
        latestHeight = cr.height;
        resizeMessagePostToParentIframe(cr.height);
      }
    }
  });

  resizeObserver.observe(containerNode)
}

function inIframe() {
  try {
    return window.self !== window.top;
  } catch (e) {
    return true;
  }
}

function resizeMessagePostToParentIframe(height) {
  const message = {
    type: 'wallarmDocsContentHeight',
    result: {
      height: `${height}px`,
      url: `${document.location.host}${document.location.pathname}`
    }
  };

  window.parent.postMessage(message, '*');
}

// Google Tag Manager

(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NQC7GWFL');

// End Google Tag Manager

/*
* Listen to the main navigation clicks.
* */
document.querySelector('.md-nav--primary').addEventListener('click', () => {
  // Reset the "Deployment options" opened states
  localStorage.removeItem('do');
});

/* ============================================================
 * Navigation tabs — edge scroll-arrows when the row overflows
 * (WADS FY26 editorial). Injects prev/next chevrons into the
 * tab bar and toggles them based on scroll position.
 * ============================================================ */
(function () {
  var CHEV =
    '<span class="chev"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
    'stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">' +
    '<path d="m9 18 6-6-6-6"/></svg></span>';

  function makeArrow(dir) {
    var b = document.createElement('button');
    b.type = 'button';
    b.className = 'md-tabs__arrow ' + dir;
    b.setAttribute('aria-label', dir === 'prev' ? 'Scroll tabs left' : 'Scroll tabs right');
    b.innerHTML = CHEV;
    return b;
  }

  function initTabScroll() {
    var list = document.querySelector('.md-tabs__list');
    if (!list) return;
    var grid = list.closest('.md-grid') || list.parentElement;
    if (!grid) return;

    var prev = grid.querySelector('.md-tabs__arrow.prev');
    var next = grid.querySelector('.md-tabs__arrow.next');
    if (!prev) { prev = makeArrow('prev'); grid.appendChild(prev); }
    if (!next) { next = makeArrow('next'); grid.appendChild(next); }

    function step() { return Math.max(160, Math.round(list.clientWidth * 0.6)); }

    function update() {
      var overflow = list.scrollWidth > list.clientWidth + 1;
      var atStart = list.scrollLeft <= 2;
      var atEnd = list.scrollLeft >= list.scrollWidth - list.clientWidth - 2;
      prev.classList.toggle('is-shown', overflow && !atStart);
      next.classList.toggle('is-shown', overflow && !atEnd);
    }

    if (!list.dataset.tabScrollWired) {
      list.dataset.tabScrollWired = '1';
      prev.addEventListener('click', function () { list.scrollBy({ left: -step(), behavior: 'smooth' }); });
      next.addEventListener('click', function () { list.scrollBy({ left: step(), behavior: 'smooth' }); });
      list.addEventListener('scroll', update, { passive: true });
      window.addEventListener('resize', update);
      // Keep the active tab in view on load
      var active = list.querySelector('.md-tabs__item--active, .md-tabs__link--active');
      if (active && active.scrollIntoView) {
        try { active.scrollIntoView({ inline: 'center', block: 'nearest' }); } catch (e) {}
      }
    }
    update();
  }

  document.addEventListener('DOMContentLoaded', initTabScroll);
  window.addEventListener('load', initTabScroll);
  if (window.document$ && typeof window.document$.subscribe === 'function') {
    window.document$.subscribe(initTabScroll);
  }
})();
