"""
Agent runner — clones docs repo, calls Anthropic API directly (no CLI),
applies changes, commits, creates GitHub PR.
"""

import json
import logging
import os
import subprocess
import tempfile

import requests

from prompts.default import build_prompt

logger = logging.getLogger(__name__)

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"


def run_doc_agent(context: dict) -> dict:
    issue_key = context["jira_issue"]["key"]
    branch_name = f"doc-agent/{issue_key.lower()}"

    with tempfile.TemporaryDirectory() as workdir:
        repo_dir = os.path.join(workdir, "docs")

        # 1. Sparse clone (docs + config only, no images)
        github_token = os.environ["GITHUB_TOKEN"]
        repo = os.environ.get("DOCS_GITHUB_REPO", "wallarm/product-docs-en")
        clone_url = f"https://x-access-token:{github_token}@github.com/{repo}.git"
        _run(f"git clone --depth=1 --filter=blob:none --sparse {clone_url} {repo_dir}")
        _run("git sparse-checkout set --skip-checks docs include mkdocs-7.x.yml mkdocs-6.x.yml "
             "mkdocs-base.yml CLAUDE.md .doc-agent", cwd=repo_dir)
        _run("git config user.email doc-agent@wallarm.com", cwd=repo_dir)
        _run("git config user.name doc-agent", cwd=repo_dir)
        _run(f"git checkout -b {branch_name}", cwd=repo_dir)

        # 2. Read existing files that Claude might need to edit
        existing_files = _read_relevant_files(context, repo_dir)

        # 3. Build prompt with everything embedded
        prompt = build_prompt(context, repo_dir=repo_dir, existing_files=existing_files)

        # 4. Save Jira images for context
        image_data = []
        for img in context.get("images", []):
            image_data.append({
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": img.get("mime", "image/png"),
                    "data": __import__("base64").b64encode(img["content"]).decode(),
                },
            })

        # 5. Call Anthropic API directly — one request, no tool calls
        logger.info(f"Calling Anthropic API for {issue_key}")
        response = _call_anthropic(prompt, image_data)
        logger.info(f"API response length: {len(response)}")

        # 6. Parse and apply file changes
        changes = _parse_changes(response)
        if not changes:
            logger.info("No changes in API response")
            return {"status": "no_changes", "issue": issue_key}

        for file_path, content in changes.items():
            full_path = os.path.join(repo_dir, file_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            with open(full_path, "w") as f:
                f.write(content)
            logger.info(f"Written: {file_path}")

        # 7. Commit & push
        _run("git add -A", cwd=repo_dir)
        summary = context["jira_issue"]["summary"]
        _run(
            f'git commit -m "docs({issue_key}): {summary}\n\nGenerated by doc-agent"',
            cwd=repo_dir,
        )
        _run(f"git push origin {branch_name}", cwd=repo_dir)

        # 8. Create GitHub PR
        pr_url = _create_github_pr(
            repo=repo,
            branch=branch_name,
            title=f"[Doc Agent] {issue_key}: {summary}",
            body=_pr_body(context),
        )

        return {"status": "pr_created", "pr_url": pr_url, "issue": issue_key}


def _read_relevant_files(context: dict, repo_dir: str) -> dict[str, str]:
    """Read files the agent is likely to edit, based on Jira ticket components."""
    files = {}
    components = [c.lower() for c in context["jira_issue"].get("components", [])]

    # Always read navigation
    for f in ["mkdocs-7.x.yml", "mkdocs-6.x.yml"]:
        path = os.path.join(repo_dir, f)
        if os.path.exists(path):
            files[f] = _read_file(path)

    # Map components to doc sections
    section_map = {
        "api discovery": "api-discovery",
        "api sessions": "api-sessions",
        "api abuse prevention": "api-abuse-prevention",
        "api protection": "api-protection",
        "agentic ai": "agentic-ai",
        "vulnerability detection": "vulnerability-detection",
    }

    sections = set()
    for comp in components:
        for key, section in section_map.items():
            if key in comp:
                sections.add(section)

    # If no component match, try to guess from summary
    if not sections:
        summary = context["jira_issue"].get("summary", "").lower()
        for key, section in section_map.items():
            if key.replace(" ", "") in summary.replace(" ", ""):
                sections.add(section)

    # Read all .md files in matched sections
    for section in sections:
        section_dir = os.path.join(repo_dir, "docs", "latest", section)
        if os.path.isdir(section_dir):
            for fname in os.listdir(section_dir):
                if fname.endswith(".md"):
                    rel_path = f"docs/latest/{section}/{fname}"
                    files[rel_path] = _read_file(os.path.join(section_dir, fname))

    return files


def _read_file(path: str) -> str:
    try:
        with open(path, "r") as f:
            return f.read()
    except (FileNotFoundError, UnicodeDecodeError):
        return ""


def _call_anthropic(prompt: str, images: list = None) -> str:
    """Single API call to Anthropic. Returns Claude's text response."""
    api_key = os.environ["ANTHROPIC_API_KEY"]

    content = []
    if images:
        content.extend(images)
    content.append({"type": "text", "text": prompt})

    resp = requests.post(
        ANTHROPIC_API_URL,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 16000,
            "messages": [{"role": "user", "content": content}],
        },
        timeout=300,
    )
    resp.raise_for_status()
    data = resp.json()

    # Extract text from response
    text_parts = []
    for block in data.get("content", []):
        if block.get("type") == "text":
            text_parts.append(block["text"])
    return "\n".join(text_parts)


def _parse_changes(response: str) -> dict[str, str]:
    """
    Parse Claude's response for file changes.
    Expected format — one or more blocks like:

    === FILE: docs/latest/api-discovery/exploring.md ===
    (full file content)
    === END FILE ===
    """
    changes = {}
    parts = response.split("=== FILE: ")
    for part in parts[1:]:  # skip text before first file
        if "=== END FILE ===" in part:
            header, rest = part.split("\n", 1)
            file_path = header.strip().rstrip(" =")
            content = rest.split("=== END FILE ===")[0]
            # Strip leading/trailing blank lines but preserve content
            content = content.strip("\n") + "\n"
            changes[file_path] = content
    return changes


def _create_github_pr(repo: str, branch: str, title: str, body: str) -> str:
    token = os.environ["GITHUB_TOKEN"]
    resp = requests.post(
        f"https://api.github.com/repos/{repo}/pulls",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        },
        json={
            "title": title,
            "body": body,
            "head": branch,
            "base": "master",
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json().get("html_url", "")


def _pr_body(context: dict) -> str:
    jira = context["jira_issue"]
    lines = [
        "## Auto-generated documentation update",
        "",
        f"**Ticket**: {jira['key']}",
        f"**Summary**: {jira['summary']}",
        "",
        "---",
        "_Generated by doc-agent. Please review and edit as needed._",
    ]
    return "\n".join(lines)


def _run(cmd: str, cwd: str = None) -> str:
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=cwd, timeout=120)
    if result.returncode != 0:
        logger.error(f"Failed: {cmd}\n{result.stderr}")
        raise RuntimeError(f"{cmd}\n{result.stderr}")
    return result.stdout
