name: Update submodules and create PR

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: master
        required: true

jobs:
  update_submodules_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if 'update-submodule' branch exists
        run: |
          if git rev-parse --quiet --verify update-submodule; then
            git checkout update-submodule
          else
            git checkout -b update-submodule
          fi

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update submodules"
          git push --set-upstream origin update-submodule

      - name: Create PR
        run: |
          hub pull-request -m "Update submodules" -b master -h update-submodule
